eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/card/**, /api/fuel/**, /api/trip/**