eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

loggin:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/card/**, /api/fuel/**