server.port: 8181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
spring:
  application.name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/ptd-auth

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - content-type
              - x-requested-with
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/card/**, /api/fuel/**, /api/trip/**
        - id: pdf-service
          uri: lb://pdf-service
          predicates:
            - Path=/api/pdf/**, /css/main.css
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicle/**
