management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
    ratelimiters:
      enabled: 'true'
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      user:
        slidingWindowType: COUNT_BASED
        failureRateThreshold: '50'
        event-consumer-buffer-size: '10'
        waitDurationInOpenState: 5s
        slidingWindowSize: '5'
        permittedNumberOfCallsInHalfOpenState: '3'
        registerHealthIndicator: 'true'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'

spring:
  kafka:
    bootstrap-servers: broker:29092
  datasource:
    password: password
    driver-class-name: org.postgresql.Driver
    username: mateuszuran
    url: jdbc:postgresql://postgres-card:5432/card-service
  zipkin:
    base-url: http://zipkin:9411

server:
  port: '0'

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
