server:
  port: 0
spring:
  application:
    name: card-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ptd-card
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update