server:
  port: 0
spring:
  application:
    name: vehicle-service
  data:
    mongodb:
      port: 27017
      host: mongodb-vehicle
      database: mongo-vehicle
      username: mateuszuran
      password: password123

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
