server:
  port: 0
spring:
  application:
    name: vehicle-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/vehicle-service
    username: mateuszuran
    password: password
  jpa:
    hibernate:
      ddl-auto: update